name: Get latest release version
on:
  schedule:
    - cron:  '0 10 * * *'
  workflow_dispatch:
jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
      - name: Fetch release version
        run: |
          curl -sL https://api.github.com/repos/DefiCh/ain/releases/latest > /tmp/release-file.json && \
          RELEASE_VERSION="$(jq -r '.tag_name' /tmp/release-file.json)" && [["$RELEASE_VERSION" -ne "null" ]] && \
          echo "$RELEASE_VERSION" > release-versions/defichain-latest.txt
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'jha749'
          git config --global user.email 'jha749@users.noreply.github.com'
          git commit -am "New release version"
          git push
